"""Update FilingRecord schema for BoT C17 payload

Revision ID: a2e2088517b9
Revises: 
Create Date: 2026-09-11 09:15:16.000462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e2088517b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Drop dependent view first
    op.execute("DROP VIEW IF EXISTS view_pcf_sectoral_summary CASCADE;")

    # 2. Existing autogenerated schema changes
    op.add_column('filings', sa.Column('reporting_year', sa.Integer(), nullable=True))
    op.add_column('filings', sa.Column('previous_year', sa.Integer(), nullable=True))
    op.add_column('filings', sa.Column('total_assets_usd', sa.Numeric(), nullable=True))
    op.add_column('filings', sa.Column('total_assets_tzs', sa.Numeric(), nullable=True))
    op.add_column('filings', sa.Column('net_worth_usd', sa.Numeric(), nullable=True))
    op.add_column('filings', sa.Column('extracted_payload', sa.JSON(), nullable=True))
    
    op.create_index('ix_filings_company_name', 'filings', ['company_name'], unique=False)
    op.create_index('ix_filings_reporting_year', 'filings', ['reporting_year'], unique=False)
    op.create_index('ix_filings_status', 'filings', ['status'], unique=False)
    
    op.drop_column('filings', 'total_tzs')
    op.drop_column('filings', 'total_usd')

    # 3. Recreate view updated to use total_assets_tzs / total_assets_usd
    op.execute("""
        CREATE OR REPLACE VIEW view_pcf_sectoral_summary AS
        SELECT 
            company_name,
            reporting_year,
            SUM(total_assets_tzs) AS total_assets_tzs,
            SUM(total_assets_usd) AS total_assets_usd
        FROM filings
        GROUP BY company_name, reporting_year;
    """)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filings', sa.Column('total_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('filings', sa.Column('total_tzs', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_filings_status'), table_name='filings')
    op.drop_index(op.f('ix_filings_reporting_year'), table_name='filings')
    op.drop_index(op.f('ix_filings_company_name'), table_name='filings')
    op.drop_column('filings', 'extracted_payload')
    op.drop_column('filings', 'net_worth_usd')
    op.drop_column('filings', 'total_assets_tzs')
    op.drop_column('filings', 'total_assets_usd')
    op.drop_column('filings', 'previous_year')
    op.drop_column('filings', 'reporting_year')
    # ### end Alembic commands ###
